Tools/Check-Setups: Fix error detection for wrong devices entries
There are some really rare cases that the setup is wrongly written. The
most common case is to add a comma after the closing bracket so the
'devices' entry isn't a dict but a tuple of dict. This creates very
unusal message (AttributeError: 'tuple' object has no attribute 'items')
and an stacktrace. This isn't really helpful for the user of the
check-setup tool. Now a hint to an additional comma after closing
bracket is given.

Change-Id: Id9bf8d6c368e1d37fde02d6267ec1ba83509cacc
Reviewed-on: https://forge.frm2.tum.de/review/c/frm2/nicos/nicos/+/38714
Tested-by: Jenkins Automated Tests <pedersen+jenkins@frm2.tum.de>
Reviewed-by: Georg Brandl <g.brandl@fz-juelich.de>