Add a guard around the TACO call.
The guard around the TACO call avoids such error messages like

TypeError: exceptions must be old-style classes or derived from BaseException, not str

due to the 'wrong' exception throwing.

Create a exception class as wrapper around the 'string' exception. Idea: B. Pedersen

The number of retries could be configured via parameter tacotries and the time
to sleep between retries via tacodelay.

Change-Id: I5fa0bdc8dba470af51ae1d0f11d99dd530e95086
Reviewed-on: https://trac.frm2.tum.de/review/2163
Tested-by: JenkinsCodeReview <bjoern_pedersen@frm2.tum.de>
Reviewed-by: Bjoern Pedersen <bjoern.pedersen@frm2.tum.de>
Reviewed-by: Jens Krueger <Jens Krüger <jens.krueger@frm2.tum.de>>
Tested-by: Jens Krueger <Jens Krüger <jens.krueger@frm2.tum.de>>