GUI: setup_panel expects int
Got the following error when trying to
open the proposal setup_panel.

Traceback (most recent call last):
  File "/home/jonas/code/nicos-mlz/nicos/nicos/
clients/gui/panels/setup_panel.py", line 117, in sizeHint
    return QSize(document.idealWidth(), int(document.size().height()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  QSize(): too many arguments
  QSize(w: int, h: int): argument 1 has unexpected type 'float'
  QSize(a0: QSize): argument 1 has unexpected type 'float'
[08:42:55] gui       : ERROR: unhandled exception in QT callback
- TypeError - arguments did not match any overloaded call:
  QSize(): too many arguments
  QSize(w: int, h: int): argument 1 has unexpected type 'float'
  QSize(a0: QSize): argument 1 has unexpected type 'float'

Change-Id: I4775d8b1905248fb7dad2fd09421d0205a413582
Reviewed-on: https://forge.frm2.tum.de/review/c/frm2/nicos/nicos/+/32497
Reviewed-by: Jens Krueger <jens.krueger@frm2.tum.de>
Tested-by: Jenkins Automated Tests <pedersen+jenkins@frm2.tum.de>